.PHONY: help test docs act deact

help:
	@echo. 
	@echo ---------------HELP-----------------------------------------
	@echo setup - run the first time when you setup the project
	@echo test  - run tests quickly with the default Python test suite
	@echo docs  - create the documentation for the project	
	@echo act   - ACTivate the conda enviroment
	@echo deact - DEACTivate the conda enviroment
	@echo ------------------------------------------------------------
	@echo.
	
setup:
	conda create -n {{cookiecutter.project_name}}
	conda activate {{cookiecutter.project_name}}
	conda install pip
	pip install -r requirements.txt
	pip install ./
	
test:
	pytest

docs:
	cd docs
	make html
	open _build/html/index.html

act:
	conda activate {{cookiecutter.project_name}}

deact:
	conda deactivate

