.PHONY: help setup test docs

help:
	@echo. 
	@echo --------------------------HELP-------------------------------
	@echo setup - run the first time when you setup the project
	@echo test  - run tests quickly with the default Python test suite
	@echo docs  - create the documentation for the project	
	@echo ------------------------------------------------------------
	@echo.
	
setup:
	pip install -r requirements.txt
	pip install ./
	pre-commit install
	
test:
	pytest

docs:
	cd docs
	make html
	open _build/html/index.html


